name: Build EXE for Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller openpyxl

    - name: Build EXE
      run: pyinstaller --onefile main.py

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: iPhoneInfoTool
        path: dist/main.exe
